### ISSUE TITLE
Discord bot crashes on exception

### ISSUE THREAD

**Issue by hemberger** [smrealms/smr#1084]
If an exception is thrown while running one of the registered DiscordCommandClient commands, then I would expect it to log the exception and then immediately notify the user in Discord, via:
https://github.com/smrealms/smr/blob/f04f2f513d88c15181368b449ac336dece2e2093/src/tools/discord/mysql_cleanup.php#L10-L16
Instead, it hangs for a while (~1 minute in DiscordPHP 6.0.1), emits an _extremely_ long error message, and then crashes. It seems like this might be related to promise handling, but I'm not entirely sure. This occurs in both DiscordPHP 6.0.1 and 5.1.3.

Here's (the beginning of) an example backtrace:

```
PHP Warning:  Uncaught PlayerNotFoundException: Invalid accountID: 6 OR gameID:1 in /smr/src/lib/Default/AbstractSmrPlayer.class.php:270
Stack trace:
#0 /smr/src/lib/Default/AbstractSmrPlayer.class.php(192): AbstractSmrPlayer->__construct(1, 6, Object(Smr\Database))
#1 /smr/src/tools/discord/GameLink.class.php(51): AbstractSmrPlayer::getPlayer(6, 1, true)
#2 /smr/src/tools/discord/commands/game.php(4): GameLink->__construct(Object(Discord\Parts\Channel\Channel), Object(Discord\Parts\User\Member))
#3 /smr/src/tools/discord/mysql_cleanup.php(11): {closure}(Object(Discord\Parts\Channel\Message), Array)
#4 [internal function]: {closure}(Object(Discord\Parts\Channel\Message), Array)
#5 /smr/vendor/team-reflex/discord-php/src/Discord/CommandClient/Command.php(258): call_user_func_array(Object(Closure), Array)
#6 /smr/vendor/team-reflex/discord-php/src/Discord/DiscordCommandClient.php(86): Discord\CommandClient\Command->handle(Object(Discord\Parts\Channel\Message), Array)
#7 /smr/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Discord\DiscordCommandClient->Discord\{closure}(Object(Discord\Parts\Channel\Message), Object(Discord\DiscordCommandClient))
#8 /smr/vendor/team-reflex/discord-php/src/Discord/Discord.php(701): Discord\Discord->emit('message', Array)
#9 /smr/vendor/react/promise/src/FulfilledPromise.php(42): Discord\Discord->Discord\{closure}(Object(Discord\Parts\Channel\Message))
#10 /smr/vendor/react/promise/src/Promise.php(66): React\Promise\FulfilledPromise->done(Object(Closure), Object(Closure))
#11 /smr/vendor/react/promise/src/Promise.php(168): React\Promise\Promise::React\Promise\{closure}(Object(React\Promise\FulfilledPromise))
#12 /smr/vendor/react/promise/src/Promise.php(231): React\Promise\Promise->settle(Object(React\Promise\FulfilledPromise))
#13 /smr/vendor/react/promise/src/Deferred.php(36): React\Promise\Promise::React\Promise\{closure}(Object(Discord\Parts\Channel\Message))
#14 /smr/vendor/team-reflex/discord-php/src/Discord/WebSockets/Events/MessageCreate.php(51): React\Promise\Deferred->resolve(Object(Discord\Parts\Channel\Message))
#15 /smr/vendor/team-reflex/discord-php/src/Discord/Discord.php(722): Discord\WebSockets\Events\MessageCreate->handle(Object(Discord\Helpers\Deferred), Object(stdClass))
#16 /smr/vendor/team-reflex/discord-php/src/Discord/Discord.php(595): Discord\Discord->handleDispatch(Object(stdClass))
#17 /smr/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Discord\Discord->handleWsMessage(Object(Ratchet\RFC6455\Messaging\Message), Object(Ratchet\Client\WebSocket))
#18 /smr/vendor/ratchet/pawl/src/WebSocket.php(72): Ratchet\Client\WebSocket->emit('message', Array)
#19 /smr/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(248): Ratchet\Client\WebSocket->Ratchet\Client\{closure}(Object(Ratchet\RFC6455\Messaging\Message), Object(Ratchet\RFC6455\Messaging\MessageBuffer))
#20 /smr/vendor/ratchet/rfc6455/src/Messaging/MessageBuffer.php(194): Ratchet\RFC6455\Messaging\MessageBuffer->processData('\x81~\x02\xE4{"t":"MESSA...')
#21 /smr/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): Ratchet\RFC6455\Messaging\MessageBuffer->onData('\x81~\x02\xE4{"t":"MESSA...')
#22 /smr/vendor/react/stream/src/Util.php(71): Evenement\EventEmitter->emit('data', Array)
#23 /smr/vendor/evenement/evenement/src/Evenement/EventEmitterTrait.php(123): React\Stream\Util::React\Stream\{closure}('\x81~\x02\xE4{"t":"MESSA...')
#24 /smr/vendor/react/stream/src/DuplexResourceStream.php(193): Evenement\EventEmitter->emit('data', Array)
#25 /smr/vendor/react/event-loop/src/StreamSelectLoop.php(245): React\Stream\DuplexResourceStream->handleData(Resource id #305)
#26 /smr/vendor/react/event-loop/src/StreamSelectLoop.php(212): React\EventLoop\StreamSelectLoop->waitForStreamActivity(2691397)
#27 /smr/vendor/team-reflex/discord-php/src/Discord/Discord.php(1369): React\EventLoop\StreamSelectLoop->run()
#28 /smr/src/tools/discord/bot.php(57): Discord\Discord->run()
#29 {main}
   thrown in /smr/src/lib/Default/AbstractSmrPlayer.class.php on line 270
PHP Stack trace:
PHP   1. {main}() /smr/src/tools/discord/bot.php:0
PHP   2. Discord\DiscordCommandClient->run() /smr/src/tools/discord/bot.php:57
PHP   3. React\EventLoop\StreamSelectLoop->run() /smr/vendor/team-reflex/discord-php/src/Discord/Discord.php:1369
PHP   4. React\EventLoop\StreamSelectLoop->waitForStreamActivity($timeout = 2691397) /smr/vendor/react/event-loop/src/StreamSelectLoop.php:212
PHP   5. React\Stream\DuplexResourceStream->handleData($stream = resource(305) of type (stream)) /smr/vendor/react/event-loop/src/StreamSelectLoop.php:245
PHP   6. React\Stream\DuplexResourceStream->emit(...
## and this is where it gets super long...
```

**Comment by hemberger** [comment]
This seems to be fixed now. I didn't track down the exact version of DiscordPHP where it was fixed, but I suspect it had something to do with the improved promise handling in v7.
